### PR TITLE
BREAKING: Delta Pager + Large Refactor

### LINKED ISSUE #25: Leaving Comments Does Not Work
**Describe the bug**
When you try to leave a comment on an unchanged/undeleted/unadded line, you'll get a nil pointer dereference:

```
http: panic serving 127.0.0.1:60819: runtime error: invalid memory address or nil pointer dereference
```

Leaving comments is definitely the hardest part of this plugin. Right now we bulk attempt to send comments to three different APIs since it's not clear whether you're leaving a comment on a deleted, changed, or added line. There's probably a better way of doing this that would also potentially address this issue.

**Expected behavior**
We should handle this more gracefully.

### PR DESCRIPTION
**Pull request by harrisoncramer**
This MR gives a major overhaul to the plugin to solve issue #25 and to enable commenting consistently.

It does this by introducing the <a href="https://github.com/dandavison/delta">delta</a> pager that enables in-line, unified diff views with line numbers in a "review" panel just like Gitlab uses. For instance:

Screenshot 2023-08-20 at 3 47 03 PM

As part of this MR I'm reconfiguring the setup function. This is a breaking change. The new setup function call expects a table in this shape (all settings are fully optional):

```lua
require("gitlab").setup({
  port = 21036,
  log_path = (vim.fn.stdpath("cache") .. "/gitlab.nvim.log"),
  popup = {
    exit = "<Esc>",
    perform_action = "<leader>s",
  },
  discussion_tree = {
    jump_to_location = "o",
    edit_comment = "e",
    delete_comment = "dd",
    reply_to_comment = "r",
    toggle_node = "t",
    toggle_resolved = "p",
    relative = "editor",
    position = "left",
    size = "20%",
    resolved = '✓',
    unresolved = ''
  },
  review_pane = {
    toggle_discussions = "<leader>d",
    added_file = "",
    modified_file = "",
    removed_file = "",
  },
  dialogue = {
    focus_next = { "j", "<Down>", "<Tab>" },
    focus_prev = { "k", "<Up>", "<S-Tab>" },
    close = { "<Esc>", "<C-c>" },
    submit = { "<CR>", "<Space>" },
  })
```

Fixes #25

### CODE REVIEW

File: lua/gitlab/review.lua [hunk 1]
```diff
@@ -0,0 +1,33 @@
+local discussions = require("gitlab.discussions")
+local state       = require("gitlab.state")
+local M           = {}
+
+M.open            = function()
+  vim.cmd.tabnew()
+
+  local term_command_template =
+  "GIT_PAGER='delta --hunk-header-style omit --line-numbers --paging never --file-added-label %s --file-removed-label %s --file-modified-label %s' git diff --cached %s"
```
Comment (levouh) [inline lua/gitlab/review.lua:9]:
```suggestion
  "GIT_PAGER='delta --hunk-header-style omit --line-numbers --paging never --file-added-label %s --file-removed-label %s --file-modified-label %s' git diff %s...HEAD"
```

File: README.md [hunk 2]
```diff
@@ -18,6 +18,7 @@ https://github.com/harrisoncramer/gitlab.nvim/assets/32515581/dfd3aa8a-6fc4-4e43
 
 - <a href="https://go.dev/">Go</a>
 - <a href="https://www.gnu.org/software/make/manual/make.html">make (for install)</a>
+- <a href"https://github.com/dandavison/delta">delta</a>
```
Comment (mnbroatch) [inline README.md:21]: link is broken in the markdown view

**Comment by levouh** [comment]
Just dropping a comment to say this is awesome, thanks for all the work @harrisoncramer.
