### PR TITLE
fix: use pagination to list MR discussions

### LINKED ISSUE #182: discussions tree does not contain all discussions
## Prerequsities

- [x] The "Troubleshooting" section of the README did not help
- [x] I've installed the required dependencies
- [x] I'm on the latest version of the plugin

## Bug Description

- The discussions tree does not contain all the discussions that are shown in Gitlab in the browser.
- The discussions are missing in the log (gitlab.nvim.log)
- The strange thing is, that I can see some of the discussions, I can successfully do things like `curl --header "PRIVATE-TOKEN: ${TOKEN}" localhost:44859/mr/info` and see information about the MR.
- I can even create new comments in nvim and they show up in Gitlab!
- The `discussions_tree.blacklist` is empty, but that should probably play no when the data is not in the log in the first place.

But I see the following in the log, notice the `page=1` in all three requests. Indeed if I replace it with `page=2`, and paste it in the browser, I can see the missing discussions!

```
-- REQUEST --
GET //api/v4/projects/42/merge_requests/296/discussions?page=1&per_page=250 HTTP/1.1
Host: _____
Accept: application/json
Private-Token: REDACTED
User-Agent: go-gitlab

-- REQUEST --
GET //api/v4/projects/42/merge_requests/296/discussions?page=1&per_page=250 HTTP/1.1
Host: _________
Accept: application/json
Private-Token: REDACTED
User-Agent: go-gitlab

-- REQUEST --
GET //api/v4/projects/42/merge_requests/296/discussions?page=1&per_page=250 HTTP/1.1
Host: __________
Accept: application/json
Private-Token: REDACTED
User-Agent: go-gitlab
```

And also this:
```
-- RESPONSE --
HTTP/2.0 200 OK
Content-Length: 272544
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json
Date: Wed, 14 Feb 2024 16:15:54 GMT
Etag: W/"02da1db492c0b81a67fac76d4298ceb3"
Link: <__________/42/merge_requests/296/discussions?id=42&noteable_id=296&page=2&per_page=100>; rel="next", <__________/42/merge_requests/296/discussions?id=42&noteable_id=296&page=1&per_page=100>; rel="first", <_____________/42/merge_requests/296/discussions?id=42&noteable_id=296&page=2&per_page=100>; rel="last"
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=63072000
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Gitlab-Meta: {"correlation_id":"01HPM6EENWJSYJ82DHBQQ2Y17R","version":"1"}
X-Next-Page: 2
X-Page: 1
X-Per-Page: 100
X-Prev-Page: 
X-Request-Id: 01HPM6EENWJSYJ82DHBQQ2Y17R
X-Runtime: 0.878132
X-Total: 136
X-Total-Pages: 2
```
And the array in the response indeed contains 100 items. Is this a bug of the go server in `gitlab.nvim`? I can't see any occurrences of "page" `gitlab.nvim/cmd` so it's probably a problem of the go-gitlab library, right?

### PR DESCRIPTION
**Pull request by jakubbortlik**
Closes #182.

This uses the `gitlab.Scan` function to iterate over all discussions and handle errors after the iterator is exhausted. The test for non-200s is no longer needed as the Scan function transforms such responses to standard errors.

This PR also limits the number of API calls for emojis by only fetching emojis for the filtered discussions.

I've tested both fixes in a large MR and it correctly fetched all discussions (that were otherwise not fetched without the pagination) and emojis.

### CODE REVIEW

File: cmd/app/list_discussions_test.go [hunk 1]
```diff
@@ -127,17 +127,6 @@ func TestListDiscussions(t *testing.T) {
...
-		request := makeRequest(t, http.MethodPost, "/mr/discussions/list", DiscussionsRequest{Blacklist: []string{}})
-		svc := middleware(
-			discussionsListerService{testProjectData, fakeDiscussionsLister{testBase: testBase{status: http.StatusSeeOther}}},
-			withMr(testProjectData, fakeMergeRequestLister{}),
-			withPayloadValidation(methodToPayload{http.MethodPost: newPayload[DiscussionsRequest]}),
-			withMethodCheck(http.MethodPost),
-		)
-		data, _ := getFailData(t, svc, request)
-		checkNon200(t, data, "Could not list discussions", "/mr/discussions/list")
-	})
```
Comment (jakubbortlik) [inline cmd/app/list_discussions_test.go:140]: `gitlab.Scan` handles errors differently, i.e., it doesn't set a non-200 status code on the response, so this test is no longer valid.

**Review by harrisoncramer — APPROVED** [review]
