### PR TITLE
Fix: Show draft replies in the correct tree

### LINKED ISSUE #392: Draft replies to comments are incorrectly shown as draft notes.
## Bug Description

Draft replies to comments are incorrectly shown as draft notes. As can be seen in the screenshots below, there are two draft comments, one of them a reply to an existing comment. There is, however, no draft note, even it the winbar says otherwise:

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Create a draft reply

## Screenshots
image
image

### PR DESCRIPTION
**Pull request by jakubbortlik**
Fixes #392.

### CODE REVIEW

File: lua/gitlab/actions/discussions/winbar.lua [hunk 1]
```diff
@@ -49,9 +49,17 @@ local function content()
...
 
   local draft_notes = require("gitlab.actions.draft_notes")
-  local inline_draft_notes = List.new(state.DRAFT_NOTES):filter(draft_notes.has_position)
-  local unlinked_draft_notes = List.new(state.DRAFT_NOTES):filter(function(note)
-    return not draft_notes.has_position(note)
+  local inline_draft_notes, unlinked_draft_notes = List.new(state.DRAFT_NOTES):partition(function(note)
+    if note.discussion_id == "" then
+      return draft_notes.has_position(note)
+    else
+      for _, discussion in ipairs(state.DISCUSSION_DATA.unlinked_discussions) do
```
Comment (jakubbortlik) [inline lua/gitlab/actions/discussions/winbar.lua:56]: I iterate over `unlinked_discussions` here because, in my experience, there are fewer of them in a typical MR.

File: lua/gitlab/actions/discussions/winbar.lua [hunk 2]
```diff
@@ -49,9 +49,17 @@ local function content()
   local resolvable_notes, resolved_notes = get_data(state.DISCUSSION_DATA.unlinked_discussions)
 
   local draft_notes = require("gitlab.actions.draft_notes")
-  local inline_draft_notes = List.new(state.DRAFT_NOTES):filter(draft_notes.has_position)
-  local unlinked_draft_notes = List.new(state.DRAFT_NOTES):filter(function(note)
-    return not draft_notes.has_position(note)
+  local inline_draft_notes, unlinked_draft_notes = List.new(state.DRAFT_NOTES):partition(function(note)
+    if note.discussion_id == "" then
```
Comment (harrisoncramer) [inline lua/gitlab/actions/discussions/winbar.lua:53]: Small thing but since this is an early return, it's clearer in my opinion if you remove the `else` block. Meaning:

```lua
if some_cond then
   return some_result
end

-- Do other work

```

Comment (jakubbortlik) [reply lua/gitlab/actions/discussions/winbar.lua:53]: Oh, sure. It's indeed clearer. Fixed.
